[package]
name = "challenge_six"
version = "0.1.0"
authors = ["Oğuz Kurt <kurt.oguz@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2.0.0"
base64 = "0.12.3"